let shopItemsData = [
  {
    id: "fone",
    name: "Lenovo",
    price: 1715,
    desc: "Lenovo-legion-5pg6",
    img: "../img/products/f1.jpg",
  },
  {
    id: "ftwo",
    name: "Asus",
    price: 670,
    desc: "Asus-tuf-gaming",
    img: "../img/products/f2.jpg",
  },
  {
    id: "fthree",
    name: "Asus",
    price: 2450,
    desc: "Asus-roq-ss17",
    img: "../img/products/f3.jpg",
  },
  {
    id: "ffour",
    name: "Lenovo",
    price: 1300,
    desc: "Lenovo-legion-5",
    img: "../img/products/f4.jpg",
  },
  {
    id: "ffive",
    name: "MSI",
    price: 1200,
    desc: "Msi-gp66-leopard",
    img: "../img/products/f5.jpg",
  },
  {
    id: "fsix",
    name: "MSI",
    price: 1200,
    desc: "Msi-pulse-gl76",
    img: "../img/products/f6.jpg",
  },
  {
    id: "fseven",
    name: "Thunderbolt",
    price: 1100,
    desc: "Thunderbolt-911",
    img: "../img/products/f7.jpg",
  },
  {
    id: "feiht",
    name: "Acer",
    price: 2280,
    desc: "Acer-predator-t500",
    img: "../img/products/f8.jpg",
  },
];
